---
title: "STA_644: Final Project"
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(sf)
library(spdep)
library(dplyr)
library(tidyr)
library(reshape2)
library(RSocrata)
library(stringr)
library(RColorBrewer)
library(knitr)
library(BAS)
library(gridExtra)
library(rjags)
```

```{r helper-funcs, echo=FALSE, message=FALSE}
normalize_weights = function(w) {
  diag(w) = 0
  rs = rowSums(w)
  rs[rs == 0] = 1
  w/rs
}

morans_I = function(y, w) {
  w = normalize_weights(w)
  n = length(y)
  y_bar = mean(y)
  num = sum(w * (y-y_bar) %*% t(y-y_bar))  
  denom = sum( (y-y_bar)^2 )
  (n/sum(w)) * (num/denom)
}
```

## Data for Time Series

Source for daily crime data: https://data.baltimorecity.gov/Public-Safety/BPD-Part-1-Victim-Based-Crime-Data/wsfq-mvij

```{r, message=FALSE, warning=FALSE}
#API request
df <- read.socrata(
  "https://data.baltimorecity.gov/resource/4ih5-d5d5.json",
  app_token = "TsdQoSnUFrpReua80oUgsxes8"
)
```

```{r}
#cleaning the data
violent = unique(df$description)[7:14]

ts_data = df %>% select(crimedate, description) %>%
  filter(description %in% violent, !str_detect(.$crimedate,"2018")) %>%
  mutate(crimedate = format(as.POSIXct(crimedate), "%Y-%m"),
         description = replace(description, str_detect(description,"ROBBERY"),"ROBBERY")) %>%
  group_by(crimedate, description) %>%
  summarize(n = n()) %>%
  spread(.,description,n) %>% ungroup() %>%
  mutate(TOTAL = rowSums(.[,-1]))
```

### Visualizing Violent Crime over Time

```{r, fig.height=5,fig.width=10}
#plotting data
stack_df = ts_data %>% melt(., id.vars=c('crimedate','TOTAL'), variable.name = 'type') %>%
  arrange(crimedate) %>%
  mutate(type = factor(type, levels = c("RAPE","HOMICIDE","SHOOTING","ROBBERY","AGG. ASSAULT")))

ggplot(stack_df, aes(x=crimedate,y=value,group=type))+
  geom_area(aes(fill=type), alpha=0.6)+
  geom_line(aes(group = type), position = "stack")+
  theme_bw()+
  theme(axis.text.x  = element_text(angle=90,hjust = 0, size=8))+
  labs(x = 'Crime Date', y='', title = 'Violent Crime in Baltimore City')
```

### Developing Univariate Time Series Model

```{r}
date = ts_data$crimedate
start = c(as.numeric(substr(date[1],1,4)),as.numeric(substr(date[1],6,7)))
end = c(as.numeric(substr(date[length(date)],1,4)),as.numeric(substr(date[length(date)],6,7)))

crime_ts = ts(ts_data$TOTAL, start=start, end=end, frequency=12)

forecast::ggtsdisplay(crime_ts, points = FALSE)
```

```{r}
forecast::ggtsdisplay(diff(crime_ts), points = FALSE)
```

```{r}
(m1.1 = forecast::Arima(crime_ts, order = c(0,1,0), 
            seasonal = list(order=c(0,0,0), period=12)))

(m1.2 = forecast::Arima(crime_ts, order = c(0,1,0), 
            seasonal = list(order=c(0,1,0), period=12)))

forecast::ggtsdisplay(m1.2$residuals, points=FALSE, lag.max=36)
```

```{r}
(m2.1 = forecast::Arima(crime_ts, order = c(0,1,0), 
            seasonal = list(order=c(1,1,0), period=12)))

(m2.2 = forecast::Arima(crime_ts, order = c(0,1,0), 
            seasonal = list(order=c(0,1,1), period=12)))

(m2.3 = forecast::Arima(crime_ts, order = c(0,1,0), 
            seasonal = list(order=c(1,1,1), period=12)))

forecast::ggtsdisplay(m2.2$residuals, points=FALSE, lag.max=36)
```

```{r}
(m3.1 = forecast::Arima(crime_ts, order = c(1,1,0), 
            seasonal = list(order=c(0,1,1), period=12)))

(m3.2 = forecast::Arima(crime_ts, order = c(0,1,1), 
            seasonal = list(order=c(0,1,1), period=12)))

(m3.3 = forecast::Arima(crime_ts, order = c(1,1,1), 
            seasonal = list(order=c(0,1,1), period=12)))

forecast::ggtsdisplay(m3.2$residuals, points=FALSE, lag.max=36)
```

### Model fit and forecasts

```{r}
library(scales)
plot(crime_ts, ylab='', main="Model - Arima (0,1,1) x (0,1,1)[12]")
lines(fitted(m3.2), col=alpha('red',0.8))
legend('topleft',legend=c('Series','Fit'),lty=c(1,1),col=c('black','red'))
```

## Data for Spatial Model

Source: https://bniajfi.org/ 

```{r}
files <- list.files("./Demo_Data", pattern="*.csv", full.names=TRUE)
for(i in 1:length(files)){
  assign(paste("df",str_extract(files[i],"(?<=Data/)[a-zA-Z]+"),sep="_"),read.csv(files[i]))
}
df_Census = df_Census %>% select(CSA2010,age18_15,age24_15,hhpov15)
df_Crime = df_Crime %>% select(CSA2010,viol15)
df_Workforce = df_Workforce %>% select(CSA2010,nilf15,unempr15,lesshs15,comprop15,numbus15)
df_Health = df_Health %>% select(CSA2010,teenbir15,tanf15,lifexp15,mort1_15)
df_Housing = df_Housing %>% select(CSA2010,vacant15,hcvhouseXX)

sp_data = plyr::join_all(list(df_Census,df_Crime,df_Workforce,df_Health,df_Housing),
                   by='CSA2010',type='left')[-c(1,57),] %>%
  mutate(CSA2010 = as.character(CSA2010)) %>%
  mutate_if(is.factor, function(x){as.character(x) %>% str_remove_all(.,",") %>% as.numeric()})
```

Source for shape files: http://gis-baltimore.opendata.arcgis.com/datasets?q=boundary 

```{r}
#shape files
bal_city = st_read('shape_files/baltimore_city_polygon.shp', quiet=TRUE, stringsAsFactors=TRUE) %>%
  st_transform(4326)
neighb = st_read('shape_files/Vital_Signs_15_Census_Demographics.shp', quiet=TRUE, stringsAsFactors=TRUE) %>%
  select(CSA2010,geometry) %>%
  mutate(CSA2010 = as.character(CSA2010))

#areal dataset
sp_sf = left_join(neighb,sp_data,by="CSA2010")
```


### Visualizing Violent Crime in 2015

```{r}
crime_df <- df %>% select(crimedate,description,longitude,latitude) %>%
  filter(description %in% violent, str_detect(.$crimedate,"2015")) %>%
  mutate(description = case_when(
    str_detect(description,"ROBBERY") ~ "ROBBERY",
    str_detect(description,"HOMICIDE|SHOOTING") ~ "HOMICIDE/SHOOTING",
    TRUE ~ description),
    latitude = as.numeric(latitude),
    longitude = as.numeric(longitude)) %>%
  filter(!is.na(latitude)&!is.na(longitude)) #%>%
  #st_as_sf(.,coords=c('longitude','latitude'), crs=4326)
```

```{r}
#old code using base plot
n = length(unique(crime_df$description))
cols = brewer.pal(n = 4, name = "Set1")
plots = sapply(c(1:n), function(x){
  plot(st_geometry(bal_city), col='lightblue', main=unique(crime_df$description)[x])
  plot(st_geometry(neighb),col='white',add=TRUE)
  data = crime_df %>%
    filter(description == unique(description)[x])
  contour(MASS::kde2d(x=data$longitude,y=data$latitude),col=cols[x],lwd=2,add=TRUE)
})
```

```{r,fig.width=10}
ggplot()+
  geom_sf(data=bal_city, fill='lightblue')+
  geom_sf(data=neighb)+
  geom_density2d(data=crime_df, aes(x=longitude,y=latitude,color=description))+
  facet_wrap( ~ description, ncol=2)+
  theme_bw()+
  theme(legend.position="none")
```


### Developing Spatial Model

```{r}
#preliminary EDA
kable(as.data.frame(-sort(-cor(sp_data[,-1])[,4])),col.names
="Correlation between Violent Crime and predictors")

### no transformation
sp.bas = bas.lm(viol15 ~ ., data=sp_data[,-1], prior="hyper-g-n",
                modelprior=uniform(),a=3,method="deterministic")
plot(sp.bas,which =1,main="viol15 ~ . No transformation")
```

```{r}
## Box-Cox transformation ##
bc_data = sp_data[,-1]

#test if any variables are not strictly positive
any(apply(bc_data,2,function(x) {any(x<=0)}))
nsp = names(which(apply(bc_data,2,function(x) {any(x<=0)})))
bc_data = bc_data %>%
  mutate_if(~min(.x)==0,~ifelse(.x==0,.0001,.x))

bc_trans <- car::powerTransform(bc_data[,-4])
summary(bc_trans)

bc.lm <- lm(viol15~age18_15+log(age24_15)+log(hhpov15)+nilf15+log(unempr15)+
              sqrt(lesshs15)+log(comprop15)+log(numbus15)+sqrt(teenbir15)+log(tanf15)+log(lifexp15)+
              sqrt(mort1_15)+log(vacant15)+sqrt(hcvhouseXX), data=bc_data)
MASS::boxcox(bc.lm)
```


```{r}
#recommended transformations
lm_data = sp_data %>% mutate(lg_viol15 = log(viol15), lg_age24_15 = log(age24_15),
                             lg_hhpov15 = log(hhpov15), lg_unempr15 = log(unempr15),
                             sqrt_lesshs15 = sqrt(lesshs15),lg_comprop15 = log(comprop15),
                             lg_numbus15 = log(numbus15), sqrt_teenbir15 = sqrt(teenbir15),
                             lg_tanf15 = log(tanf15), lg_lifexp15 = log(lifexp15),
                             sqrt_mort1_15 = sqrt(mort1_15), lg_vacant15 = log(vacant15),
                             sqrt_hcvhouseXX = sqrt(hcvhouseXX)) %>%
  select(-c(viol15,age24_15,hhpov15,unempr15,lesshs15,comprop15,numbus15,
            teenbir15,tanf15,lifexp15,mort1_15,vacant15,hcvhouseXX))
GGally::ggpairs(lm_data[,c(4,2:3,5:6)])
GGally::ggpairs(lm_data[,c(4,7:10)])
GGally::ggpairs(lm_data[,c(4,11:16)])
```

```{r}
#variable selection using BMA
df.bas = bas.lm(lg_viol15 ~ ., data=lm_data[,-1], prior="hyper-g-n",
                modelprior=uniform(),a=3,method="deterministic")
sp_resp = sp_sf %>% select(CSA2010,viol15)

#diagnostics(df.bas, type="pip")
par(mfrow=c(2,2))
plot(df.bas)
#plot(coef(df.bas),ask = FALSE)
par(mfrow=c(1,1))
bas_pred = lm_data[,c("CSA2010",names(lm_data %>% select(-c(lg_viol15,CSA2010)))[df.bas$probne0[-1]>=0.5])]
bas_data = left_join(sp_resp,bas_pred,by="CSA2010")

#variable selection using stepwise selection
reg1 = lm(lg_viol15~.,data = lm_data[,-1])

aic_step = step(reg1,trace = F, direction = "backward") 
aic_pred = lm_data[,c("CSA2010",names(aic_step$coefficients)[-1])]
aic_data = left_join(sp_resp,aic_pred,by="CSA2010")

bic_step = step(reg1,k = log(nrow(lm_data)),trace = F,direction = "backward")
bic_pred = lm_data[,c("CSA2010",names(bic_step$coefficients)[-1])]
bic_data = left_join(sp_resp,bic_pred,by="CSA2010")
```

```{r}
ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data,aes(fill=log(viol15)))+
  #scale_fill_gradient(low="blue", high="red")+
  theme_bw()
```

Map for manual readjustment of adjacency matrix: https://bniajfi.org/wp-content/uploads/2014/04/Zip-Codes-and-CSA-2010.pdf

```{r, message=FALSE}
## adjacency matrix ##
W = 1*st_touches(bas_data, sparse = FALSE)

#adjust for issues with geometries
csa = bas_data$CSA2010[rowSums(W)==0]
ngh1 = c("Cherry Hill","Westport/Mount Winans/Lakeland")
ngh2 = c("Downtown/Seton Hill","Oldtown/Middle East","Fells Point")

W[bas_data$CSA2010==csa[1],bas_data$CSA2010 %in% ngh1]=1
W[bas_data$CSA2010 %in% ngh1,bas_data$CSA2010==csa[1]]=1
W[bas_data$CSA2010==csa[2],bas_data$CSA2010 %in% ngh2]=1
W[bas_data$CSA2010 %in% ngh2,bas_data$CSA2010==csa[2]]=1
listW = mat2listw(W)

#spatial autoco.
moran.test(bas_data$viol15, listW)
moran.test(log(bas_data$viol15), listW)
```

```{r}
#spatial autoco. partialing out covariates
l = lm(log(viol15)~lg_comprop15+lg_lifexp15,data=bas_data)
summary(l)

bas_data = bas_data %>%
  mutate(
    lm_pred = l$fitted.values,
    lm_resid = l$residuals
  )

p1 <- ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data,aes(fill=lm_pred))+
  labs(title="Linear Model Predictions",fill="")+
  theme_bw()

p2 <- ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data,aes(fill=lm_resid))+
  labs(title="Linear Model Residuals",fill="")+
  theme_bw()

grid.arrange(p1, p2, ncol=2)

moran.test(bas_data$lm_resid, listW)
```

### Areal Data Models

```{r}
#CAR and SAR models
bal_car = spautolm(formula = log(viol15) ~ lg_comprop15+lg_lifexp15, data = bas_data, 
                  listw = listW, family = "CAR")
summary(bal_car)

bal_sar = spautolm(formula = log(viol15) ~ lg_comprop15+lg_lifexp15, data = bas_data, 
                  listw = listW, family = "SAR")
summary(bal_sar)

bas_data = bas_data %>%
  mutate(car_pred = bal_car$fit$fitted.values, car_resid = bal_car$fit$residuals,
         sar_pred = bal_sar$fit$fitted.values, sar_resid = bal_sar$fit$residuals)
```


```{r}
#car fit and residuals
car_f <- ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data, aes(fill=car_pred))+
  labs(title="CAR Model Predictions",fill="")+
  theme_bw()

car_r <- ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data, aes(fill=car_resid))+
  labs(title="CAR Model Residuals",fill="")+
  theme_bw()
grid.arrange(car_f, car_r, ncol=2)
```

```{r}
#sar fit and residuals
sar_f <- ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data, aes(fill=sar_pred))+
  labs(title="SAR Model Predictions",fill="")+
  theme_bw()

sar_r <- ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data, aes(fill=sar_resid))+
  labs(title="SAR Model Predictions",fill="")+
  theme_bw()
grid.arrange(sar_f, sar_r, ncol=2)
```

```{r}
#comparing residuals - considering removing this?
par(mfrow=c(1,2))
plot(bas_data$car_resid, bas_data$sar_resid, main="CAR vs SAR Residuals",xlab="",ylab="")
abline(a = 0, b=1)
qqnorm(bas_data$car_resid, main = "CAR Residuals");qqline(bas_data$car_resid)
#qqnorm(bas_data$sar_resid, main = "SAR Residuals");qqline(bas_data$sar_resid)
par(mfrow=c(1,1))

moran.test(bas_data$car_resid, listW)
moran.test(bas_data$sar_resid, listW)
```

### Bayesian Versions of the model

```{r}
#Bayesian CAR model
D = diag(rowSums(W))
X = model.matrix(l)
y = log(bas_data$viol15)

car_model = "model{
  for(i in 1:length(y)) {
    y[i] ~ dnorm(mu[i],tauw)
    y_pred[i] ~ dnorm(mu[i],tauw)
    mu[i] = X[i,] %*% beta + omega[i]
  }
  #priors for beta
  for(i in 1:3) {
    beta[i] ~ dnorm(0,0.0001)
  }

  #priors for sigma2_w
  tauw ~ dgamma(1,1)
  sigma2w = 1/tauw

  omega ~ dmnorm(rep(0,length(y)), tau * (D - phi*W))
  sigma2 = 1/tau
  tau ~ dgamma(2, 2)
  phi ~ dunif(0,0.99)
}"
```


```{r}
if (!file.exists("car_model.Rdata")) {
  m = rjags::jags.model(
    textConnection(car_model), 
    data = list(
      D = D,
      y = y,
      X = X,
      W = W
    ),
    n.adapt=25000
  )

  update(m, n.iter=25000)
  
  car_coda = rjags::coda.samples(
    m, variable.names=c("sigma2","tau", "beta", "omega", "phi", "y_pred","sigma2w","tauw"),
    n.iter=50000, thin=50
  )
  save(car_coda, m, file="car_model.Rdata")
} else {
  load("car_model.Rdata")
}

beta_params = tidybayes::gather_samples(car_coda,beta[i]) %>%
  ungroup() %>%
  mutate(term = paste0(term,"[",i,"]"))

ar_params = tidybayes::gather_samples(car_coda,sigma2,phi,sigma2w)

omega = tidybayes::gather_samples(car_coda,omega[i])
y_pred = tidybayes::gather_samples(car_coda,y_pred[i])
```

```{r}
ggplot(beta_params, aes(x=.iteration, y=estimate, color=term)) +
  geom_line() +
  facet_grid(term~., scales="free_y") +
  guides(color=FALSE)

ggplot(ar_params, aes(x=.iteration, y=estimate, color=term)) +
  geom_line() +
  facet_grid(term~., scales="free_y") +
  guides(color=FALSE)
```

```{r}
bas_data = bas_data %>% 
  mutate(
    bayes_car_pred = y_pred %>% summarize(pred = mean(estimate)) %>% pull(pred), 
    bayes_car_resid = log(viol15) - car_pred
  )

car_f <- ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data, aes(fill=bayes_car_pred))+
  labs(title="Bayes CAR Model Predictions",fill="")+
  theme_bw()

car_r <- ggplot()+
  geom_sf(data=bal_city, fill='grey')+
  geom_sf(data=bas_data, aes(fill=bayes_car_resid))+
  labs(title="Bayes CAR Model Residuals",fill="")+
  theme_bw()
grid.arrange(car_f, car_r, ncol=2)
moran.test(bas_data$bayes_car_resid, listW)
```


